[book]
title = "Advent of Mojo"
authors = ["Erica Sadun"]
language = "en"

[output.html]
additional-css = [
    "theme/css/advent.css",
    "theme/css/highlight.css",
]
additional-js = [
    "theme/mojolang.js",
]