[workspace]
authors = ["Erica Sadun <@fairlydurable>", "Michael Dunn-OConnor <@dunnoconnor>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "advent-of-mojo"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
book = "mdbook build"
serve = "mdbook serve"
test = "bash tests/run_tests.sh"

[dependencies]
mojo = ">=1.0.0b3.dev2026072217,<2"
mdbook = ">=0.5.4,<0.6"
